{
  "totalSize": 1,
  "done": true,
  "records": [
    {
      "attributes": {
        "type": "Opportunity",
        "url": "/services/data/v64.0/sobjects/Opportunity/{{opportunity_id}}"
      },
      "Id": "{{opportunity_id}}",
      "IsDeleted": false,
      "AccountId": "{{account_id}}",
      "IsPrivate": false,
      "Name": "{{opportunity_name}}",
      "Description": "{{description}}",
      "StageName": "{{stage_name}}",
      "Amount": "{{amount}}",
      "Probability": "{{probability}}",
      "ExpectedRevenue": "{{expected_revenue}}",
      "TotalOpportunityQuantity": "{{total_opportunity_qty}}",
      "CloseDate": "{{close_date}}",
      "Type": "{{opportunity_type}}",
      "NextStep": "{{next_step}}",
      "LeadSource": "{{lead_source}}",
      "IsClosed": "{{is_closed}}",
      "IsWon": "{{is_won}}",
      "ForecastCategory": "{{forecast_category}}",
      "ForecastCategoryName": "{{forecast_category_name}}",
      "CampaignId": "{{campaign_id}}",
      "HasOpportunityLineItem": "{{has_line_item}}",
      "Pricebook2Id": "{{pricebook_id}}",
      "OwnerId": "{{owner_id}}",
      "CreatedDate": "{{created_date}}",
      "CreatedById": "{{created_by_id}}",
      "LastModifiedDate": "{{last_modified_date}}",
      "LastModifiedById": "{{last_modified_by_id}}",
      "SystemModstamp": "{{system_modstamp}}",
      "LastActivityDate": "{{last_activity_date}}",
      "PushCount": "{{push_count}}",
      "LastStageChangeDate": "{{last_stage_change_date}}",
      "FiscalQuarter": "{{fiscal_quarter}}",
      "FiscalYear": "{{fiscal_year}}",
      "Fiscal": "{{fiscal}}",
      "ContactId": "{{contact_id}}",
      "LastViewedDate": "{{last_viewed_date}}",
      "LastReferencedDate": "{{last_referenced_date}}",
      "SyncedQuoteId": "{{synced_quote_id}}",
      "HasOpenActivity": "{{has_open_activity}}",
      "HasOverdueTask": "{{has_overdue_task}}",
      "LastAmountChangedHistoryId": "{{last_amount_changed_history_id}}",
      "LastCloseDateChangedHistoryId": "{{last_close_date_changed_history_id}}",
      "DeliveryInstallationStatus__c": "{{delivery_status}}",
      "TrackingNumber__c": "{{tracking_number}}",
      "OrderNumber__c": "{{order_number}}",
      "CurrentGenerators__c": "{{current_generators}}",
      "MainCompetitors__c": "{{main_competitors}}",
      "Phone__c": "{{phone}}",
      "Email__c": "{{email}}",
      "Proposed_Discount__c": "{{proposed_discount}}",
      "Discount__c": "{{discount}}",
      "MRR__c": "{{mrr}}",
      "ARR__c": "{{arr}}",
      "Approved__c": "{{approved}}",
      "Segment__c": "{{segment}}",
      "Region__c": "{{region}}"
    }
  ]
}

